[package]
name = "rust-99-problems"
version = "0.1.0"
authors = ["Marco Wittig <marco.wittig@jambit.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
